baseurl = "https://agaricus.xyz/"
title = "A G A R I C U S"
author = "Joaquin Pereyra"
canonifyurls = true
languagecode = "en"
theme = "hugo-coder"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "tango"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Agaricus"
  avatarurl = "avatar_2.png"
  faviconSVG = "/favicon.ico"
  author = "Joaquin Pereyra"
  description="Agaricus, like the agora: wild, unpredictable, and fruitful."
  highlightjs = true
  highlightjslanguages = ["r", "python", "golang"]
  uselatex = true
  progressively = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 3
    
[[params.social]]
  icon = "fa fa-github fa-2x"
  weight = 1
  name = "Github"
  url = "https://github.com/joaquinlpereyra"

[[params.social]]
  icon = "fa fa-twitter fa-2x"
  weight = 2
  name = "Twitter"
  url = "https://x.com/0xmatebabe"

[[params.social]]
  icon = "fa fa-linkedin fa-2x"
  name = "Linkedin"
  weight = 3
  url = "https://linkedin.com/in/joaquinlpereyra"
