baseurl = "https://joaquin.site/"
languageCode = "en-us"
title = "personal ramblings"
theme = "hugo-xmin"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Public Key"
    url = "/key/"
    weight = 2
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Joaquin's personal ramblings"
    footer = "&copy; [Joaquin](https://joaquin.site) | [Github](https://github.com/joaquinlpereyra) | [Linkedin](https://www.linkedin.com/in/joaquinlpereyra/)"
