baseurl = "https://agaricus.xyz"
title = "Agaricus Security"
author = "Joaquin Pereyra"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = false
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About Agaricus"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Public Key"
    url = "/key/"
    weight = 3
